name: GameBoy Tests
on: [push]

jobs:
  GameBoy-Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: '2.2.0'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - working-directory: ./gameboy
      name: "Testing GameBoy emulator"
      run: nimble test
